### ISSUE TITLE
Black images

### ISSUE THREAD

**Issue by hysts** [rois-codh/kmnist#1]
It seems there are black images in KMNIST training/testing data.

Indices of black images in training data:
13109, 13415, 13442, 23328, 24234, 26413, 28814, 29279, 33433, 38946, 42827, 44186, 50110, 55361, 55533, 56969, 57915

Index of black image in testing data:
9677

I checked both MNIST format files and NumPy format ones.

**Comment by mxbi** [comment]
Thanks for finding this and bringing it to our attention :) It seems to have been an issue with preprocessing that wasn't caught when the data was manually checked.

Since the dataset has only just been released we plan to release an updated version soon with the black images fixed in all three datasets.

**Comment by hysts** [comment]
Great! Looking forward to it. :)

**Comment by mxbi** [comment]
Updated dataset released back in February fixes this. Thank you again for reporting this!
